config/routes.rb
Rails.application.routes.draw do
  resources :products, only: :index do
    resources :orders, only: :create
  end

  resources :orders, only: :index
  
  root 'products#index'
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :products, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @product = Product.find(params[:product_id])
    @order = Order.new(product: @product, user: current_user)
    
    if @order.save
      redirect_to products_path, notice: 'La orden ha sido ingresada'
    else
      redirect_to products_path, alert: 'La orden NO ha sido ingresada'
    end
  end

  def index
    @orders = current_user.orders
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <% if user_signed_in? %>
        <a href="<%= root_path %>" class="nav-link">Bienvenido: <%= current_user.email %></a>
        <a href="<%= destroy_user_session_path %>" data-method="DELETE" class="btn btn-outline-danger ml-2">Salir</a>
        <a class="btn btn-outline-success ml-2" href="<%= orders_path %>">Carro de Compras</a>
      <% else %>    
        <a href="<%= new_user_session_path %>" class="btn btn-outline-primary">Ingresar</a>
        <a href="<%= new_user_registration_path %>" class="btn btn-outline-primary ml-2">Registrarse</a>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Semana1902</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<table class="table">
  <% @orders.each do |order| %>
    <tr>
      <td> <%= order.product.name %> </td>
      <td> <%= order.product.price %> </td>
    </tr>
  <% end %>
    <tr>
      <td> Total: </td>
      <td> <%= @orders.map { |order| order.product.price }.sum %> </td>
    </tr>
</table>

app/views/products/index.html.erb
<div class="row mt-3">
  <% @products.each_slice(3) do |row| %>
    <% row.each do |product| %>
    <div class="col-sm-12 col-md-4 col-lg-4">
      <div class="card">
        <%= image_tag product.photo, class: 'card-img-top' %>
        <div class="card-body text-center">
          <h5> <%= product.name %> </h5>
          <p> <%= product.price %> </p>
          <%= link_to 'Comprar', product_orders_path(product), class: 'btn btn-success', method: :post %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="w-100" style="margin-top: 20px"></div>
  <% end %>
</div>